import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  defaultSidebar: [
    {
      type: 'category',
      label: 'Introduction to AI-Driven Development',
      // Sahi ID use kiya: 'intro'
      link: {
        type: 'doc',
        id: 'intro', 
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'intro',
        }
      ],
    },
    {
      type: 'category',
      label: 'Spec Kit & Prompt Engineering',
      // Sahi ID use kiya: 'spec-kit/spec-kit' (jo available IDs mein tha)
      link: {
        type: 'doc',
        id: 'spec-kit/spec-kit', 
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'spec-kit',
        }
      ],
    },
    {
      type: 'category',
      label: 'Deployment and Next Steps',
      // Sahi ID use kiya: 'deployment/deployment-guide' (jo available IDs mein tha)
      link: {
        type: 'doc',
        id: 'deployment/deployment-guide', 
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'deployment',
        }
      ],
    },
  ],
};

export default sidebars;