import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Docusaurus ko yahan 'defaultSidebar' chaiye, jo hamare chapters ko define karega.

const sidebars: SidebarsConfig = {
  // Hamara custom sidebar, jo 'docusaurus.config.js' ke navbar se linked hai.
  defaultSidebar: [
    {
      type: 'category',
      label: 'Introduction to AI-Driven Development',
      items: [
        {
          type: 'autogenerated',
          dirName: 'intro',
        }
      ],
    },
    {
      type: 'category',
      label: 'Spec Kit & Prompt Engineering',
      // Iske andar woh files aayengi jo docs/spec-kit/ folder mein hongi
      items: [
        {
          type: 'autogenerated',
          dirName: 'spec-kit', // docs/spec-kit folder se content uthayega
        }
      ],
    },
    {
      type: 'category',
      label: 'Deployment and Next Steps',
      // Iske andar woh files aayengi jo docs/deployment/ folder mein hongi
      items: [
        {
          type: 'autogenerated',
          dirName: 'deployment', // docs/deployment folder se content uthayega
        }
      ],
    },
  ],

  // Aap is default tutorial sidebar ko ignore kar sakte hain, agar woh pehle se nahi ho.
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}], 
};

export default sidebars;